/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthedSubscriptionsRouteImport } from './routes/_authed/subscriptions'
import { Route as AuthedSettingsRouteImport } from './routes/_authed/settings'
import { Route as AuthedReleasesRouteImport } from './routes/_authed/releases'
import { Route as AuthedPullsRouteImport } from './routes/_authed/pulls'
import { Route as AuthedIssuesRouteImport } from './routes/_authed/issues'
import { Route as AuthedDiscoverRouteImport } from './routes/_authed/discover'
import { Route as AuthedDashboardRouteImport } from './routes/_authed/dashboard'
import { Route as AuthedCommitsRouteImport } from './routes/_authed/commits'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedSubscriptionsRoute = AuthedSubscriptionsRouteImport.update({
  id: '/subscriptions',
  path: '/subscriptions',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedSettingsRoute = AuthedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedReleasesRoute = AuthedReleasesRouteImport.update({
  id: '/releases',
  path: '/releases',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedPullsRoute = AuthedPullsRouteImport.update({
  id: '/pulls',
  path: '/pulls',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedIssuesRoute = AuthedIssuesRouteImport.update({
  id: '/issues',
  path: '/issues',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedDiscoverRoute = AuthedDiscoverRouteImport.update({
  id: '/discover',
  path: '/discover',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedDashboardRoute = AuthedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedCommitsRoute = AuthedCommitsRouteImport.update({
  id: '/commits',
  path: '/commits',
  getParentRoute: () => AuthedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/commits': typeof AuthedCommitsRoute
  '/dashboard': typeof AuthedDashboardRoute
  '/discover': typeof AuthedDiscoverRoute
  '/issues': typeof AuthedIssuesRoute
  '/pulls': typeof AuthedPullsRoute
  '/releases': typeof AuthedReleasesRoute
  '/settings': typeof AuthedSettingsRoute
  '/subscriptions': typeof AuthedSubscriptionsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/commits': typeof AuthedCommitsRoute
  '/dashboard': typeof AuthedDashboardRoute
  '/discover': typeof AuthedDiscoverRoute
  '/issues': typeof AuthedIssuesRoute
  '/pulls': typeof AuthedPullsRoute
  '/releases': typeof AuthedReleasesRoute
  '/settings': typeof AuthedSettingsRoute
  '/subscriptions': typeof AuthedSubscriptionsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authed/commits': typeof AuthedCommitsRoute
  '/_authed/dashboard': typeof AuthedDashboardRoute
  '/_authed/discover': typeof AuthedDiscoverRoute
  '/_authed/issues': typeof AuthedIssuesRoute
  '/_authed/pulls': typeof AuthedPullsRoute
  '/_authed/releases': typeof AuthedReleasesRoute
  '/_authed/settings': typeof AuthedSettingsRoute
  '/_authed/subscriptions': typeof AuthedSubscriptionsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/commits'
    | '/dashboard'
    | '/discover'
    | '/issues'
    | '/pulls'
    | '/releases'
    | '/settings'
    | '/subscriptions'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/commits'
    | '/dashboard'
    | '/discover'
    | '/issues'
    | '/pulls'
    | '/releases'
    | '/settings'
    | '/subscriptions'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/login'
    | '/_authed/commits'
    | '/_authed/dashboard'
    | '/_authed/discover'
    | '/_authed/issues'
    | '/_authed/pulls'
    | '/_authed/releases'
    | '/_authed/settings'
    | '/_authed/subscriptions'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRoute: typeof AuthedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/subscriptions': {
      id: '/_authed/subscriptions'
      path: '/subscriptions'
      fullPath: '/subscriptions'
      preLoaderRoute: typeof AuthedSubscriptionsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/settings': {
      id: '/_authed/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthedSettingsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/releases': {
      id: '/_authed/releases'
      path: '/releases'
      fullPath: '/releases'
      preLoaderRoute: typeof AuthedReleasesRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/pulls': {
      id: '/_authed/pulls'
      path: '/pulls'
      fullPath: '/pulls'
      preLoaderRoute: typeof AuthedPullsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/issues': {
      id: '/_authed/issues'
      path: '/issues'
      fullPath: '/issues'
      preLoaderRoute: typeof AuthedIssuesRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/discover': {
      id: '/_authed/discover'
      path: '/discover'
      fullPath: '/discover'
      preLoaderRoute: typeof AuthedDiscoverRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/dashboard': {
      id: '/_authed/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthedDashboardRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/commits': {
      id: '/_authed/commits'
      path: '/commits'
      fullPath: '/commits'
      preLoaderRoute: typeof AuthedCommitsRouteImport
      parentRoute: typeof AuthedRoute
    }
  }
}

interface AuthedRouteChildren {
  AuthedCommitsRoute: typeof AuthedCommitsRoute
  AuthedDashboardRoute: typeof AuthedDashboardRoute
  AuthedDiscoverRoute: typeof AuthedDiscoverRoute
  AuthedIssuesRoute: typeof AuthedIssuesRoute
  AuthedPullsRoute: typeof AuthedPullsRoute
  AuthedReleasesRoute: typeof AuthedReleasesRoute
  AuthedSettingsRoute: typeof AuthedSettingsRoute
  AuthedSubscriptionsRoute: typeof AuthedSubscriptionsRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedCommitsRoute: AuthedCommitsRoute,
  AuthedDashboardRoute: AuthedDashboardRoute,
  AuthedDiscoverRoute: AuthedDiscoverRoute,
  AuthedIssuesRoute: AuthedIssuesRoute,
  AuthedPullsRoute: AuthedPullsRoute,
  AuthedReleasesRoute: AuthedReleasesRoute,
  AuthedSettingsRoute: AuthedSettingsRoute,
  AuthedSubscriptionsRoute: AuthedSubscriptionsRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
